### ISSUE TITLE
Incompatibility between versions of together and numpy

### ISSUE THREAD

**Issue by teodororo** [EZ-hwh/AutoScraper#4]
I've tried to install the dependencies as the README.md instructs:
`
pip install -r requirements.txt
`
 and the following error appeared:
```
ERROR: Cannot install -r requirements.txt (line 10) and numpy==1.23.3 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested numpy==1.23.3
    together 1.1.2 depends on numpy>=1.23.5; python_version < "3.12"

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict
```
version "1.0.1" works just fine. I can't tell if this affects the rest of the code somehow.

**Comment by LoyAngel** [comment]
Just enter the requirements.txt file, and modify the 'numpy==1.23.3' to 'modify==1.23.5'. Hope it works for you.

**Comment by LoyAngel** [comment]
Just enter the requirements.txt file, and modify the 'numpy==1.23.3' to 'numpy==1.23.5'. Hope it works for you.

**Comment by EZ-hwh** [comment]
谢谢你，文件我已经收到！

**Comment by EZ-hwh** [comment]
Thanks for your suggestion. Package together is an API calling package, which can be replaced by other LLM call methods, so you can ignore the error reported for the together package. We'll update the requirement.txt file to fix it out.
